version: '3.8'

services:
  solar-system-simulation-web:
    build: .
    image: ghcr.io/kuranez/solar-system-simulation-web:latest
    user: "10000:1003"  # webadmin:psacln
    ports:
      - "5000:5000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1